apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: khhfcilzv-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:94bfba59e7d8f82fdaea379dd311573396315aac@sha256:989efdef9f888d8eff88ead0cd12b358f8932dc81eeafa8f3b4e9b987373e637
          name: container-image
